### ISSUE TITLE
No JSON object could be decoded - Error

### ISSUE THREAD

**Issue by diziphoria** [lbryio/lbry-setup#6]
hi, since we got a note on google groups to run setup again to update (bug in a blockchain client) - I've got this error after.

Same happens with GUI client. It starts - but gives a pop up and closes itself with same error in console.

```MacBook-Pro:~ null$ lbrycrdd -server -gen -daemon```
```LBRYcrd server starting```

```MacBook-Pro:~ null$ lbrynet-console```
```Loading databases...```
```Databases loaded.```
```Connecting to lbrycrdd...```
```No JSON object could be decoded```
```Unhandled error in Deferred:```

```Traceback (most recent call last):```
```  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner```
    ```self.run()```
```  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run```
```    self.__target(*self.__args, **self.__kwargs)```
```  File "/usr/local/lib/python2.7/site-packages/Twisted-15.4.0-py2.7-macosx-10.11-x86_64.egg/twisted/_threads/_threadworker.py", line 46, in work```
```    task() ```
```  File "/usr/local/lib/python2.7/site-packages/Twisted-15.4.0-py2.7-macosx-10.11-x86_64.egg/twisted/_threads/_team.py", line 190, in doWork```
```    task() ```
``` exception caught here ```
```  File "/usr/local/lib/python2.7/site-packages/Twisted-15.4.0-py2.7-macosx-10.11-x86_64.egg/twisted/python/threadpool.py", line 241, in inContext```
```    result = inContext.theWork()```
```  File "/usr/local/lib/python2.7/site-packages/Twisted-15.4.0-py2.7-macosx-10.11-x86_64.egg/twisted/python/threadpool.py", line 257, in <lambda>```
```    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)```
```  File "/usr/local/lib/python2.7/site-packages/Twisted-15.4.0-py2.7-macosx-10.11-x86_64.egg/twisted/python/context.py", line 118, in callWithContext```
```    return self.currentContext().callWithContext(ctx, func, *args, **kw)```
```  File "/usr/local/lib/python2.7/site-packages/Twisted-15.4.0-py2.7-macosx-10.11-x86_64.egg/twisted/python/context.py", line 81, in callWithContext```
```    return func(*args,**kw)```
```  File "/usr/local/lib/python2.7/site-packages/lbrynet-0.0.4-py2.7.egg/lbrynet/core/Session.py", line 261, in threaded_unset_upnp```
```    u.selectigd() ```
``` exceptions.Exception: No UPnP device discovered ```

**Comment by jackrobison** [comment]
This might be from a malformed lbrycrd.conf

**Comment by diziphoria** [comment]
As for error - it disappeared after doing npm/brew upgrade to latest versions. 

However JSON problem still there. I've also thought that this has something to do with lbrycrd.conf - so removed it completely and tried starting daemon without it - it prompted with proposed user/pwd to include in that file, and I did, however, no luck. 

Any chance you could share example of how it should look?

**Comment by jackrobison** [comment]
The following should generate a proper .conf file, presuming your lbrycrd_dir is ~/.lbrycrd

`echo -e "rpcuser=lbryrpc\nrpcpassword=$(xxd -l 16 -p /dev/urandom)" > "/Users/${USER}/.lbrycrd/lbrycrd.conf"`

Here's a zipped example of a file the above creates:
[lbrycrd.conf.zip](https://github.com/lbryio/lbry-setup/files/67746/lbrycrd.conf.zip)

Also, be sure you `lbrycrd-cli stop` before testing the new conf, otherwise the server will keep running and lbrynet-daemon/console/gui won't be able to log into it. The `No JSON object could be decoded` error is one that I've only gotten when I've had a bad conf file.

**Comment by diziphoria** [comment]
overlooked ***presuming your lbrycrd_dir is ~/.lbrycrd*** bit and was updating ~/Library/Application Support/lbrycrd/

Updated to the same in both places and no error anymore. 

thanks @jackrobison
