### ISSUE TITLE
Missing cython

### ISSUE THREAD

**Issue by michalvalasek** [lbryio/lbry-setup#8]
After I installed LBRY on an Ubuntu box (via the install script), I tried to install the python console/gui. The installation failed due to missing *Cython*:
```
RuntimeError: Cython must be installed to build unqlite-python.
```

I installed the *cython* package (`apt-get install cython`)  and run the install script (`python setup.py install`) again - this time it finished OK and the console is working.

**Comment by jackrobison** [comment]
Fixed here: https://github.com/lbryio/lbry/commit/b0af31a71c4f53518844bf73464618ac3b958448
